### ISSUE TITLE
make test not working

### ISSUE THREAD

**Issue by prassanna-ravishankar** [yati-sagade/opencv-ndarray-conversion#9]
After I had cloned your repository, I ran 'make' and everything was fine - no errors.
But for 'make test', I get the following output:-

env python2 -m test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/prassanna/Development/workspace/opencv-ndarray-conversion/test.py", line 7, in <module>
    raise ImportError('Could not import the examples module. Did you run make?')
ImportError: Could not import the examples module. Did you run make?
make: **\* [test] Error 1

My earlier make output is here : https://gist.github.com/4338f288aec0cabe2b2a.git

**Comment by yati-sagade** [comment]
Do you see a file called `examples.so` in the same directory as you ran `make` in?

**Comment by JohnnyY8** [comment]
Hi everyone:

I have seen the file called `examples.so` as following:
![image](https://cloud.githubusercontent.com/assets/12611573/15647747/1eb8c512-2698-11e6-9b30-dd0c40a42da9.png)
But when I make test, still get the error:
env python2 -m test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/tools/tempcodes/opencv-ndarray-conversion-master/test.py", line 9, in <module>
    raise ImportError('Could not import the examples module. Did you run make?')
ImportError: Could not import the examples module. Did you run make?
make: **\* [test] Error 1

Can you guys give me any help?
Thanks a lot! @yati-sagade @atemysemicolon

**Comment by harshmunshi** [comment]
any help on this? I'm having the same issue

**Comment by yati-sagade** [comment]
Hey! can you try pulling the import in test.py line 9 out of the try..except block to see what the actual error was? I should not have hidden the error like that :/

**Comment by hyperchris** [comment]
I got the same issue and the "examples.so" is already generated. Here is the output of the import error: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./examples.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv
`


Btw I'm using OpenCV3 so I have to change the definition of class NumpyAllocator in conversion.cpp to the opencv3's form [here](https://github.com/opencv/opencv/blob/master/modules/python/src2/cv2.cpp). I have to change this to get avoid of the issue in #12 


Any idea?
